# -*- coding: utf-8 -*-
"""Transition_Based_Dependency_Parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNMs6AG31cM93vrAWvBHzolbZXSZ40zX
"""